=== henadalGH/BD2/Unidad_1/ejercicio8.dtd
<!ELEMENT agenda (eventos)>
<!ELEMENT eventos (evento+)>
<!ELEMENT evento (titulo, fecha, hora, descripción)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT descripción (#PCDATA)>

=== henadalGH/BD2/Unidad_1/ejercicio8.xml
<!DOCTYPE agenda SYSTEM "ejercicio8.dtd">
<agenda>
    <eventos>
        <evento>
            <titulo>Conferecia tecnologica</titulo>
            <fecha>2024-04-15</fecha>
            <hora>10:00</hora>
            <descripción>Charla sobre las ultimas tendencias tecnologicas</descripción>
        </evento>

        <evento>
            <titulo>Festival de arte</titulo>
            <fecha>2024-04-20</fecha>
            <hora>15:30</hora>
            <descripción>Exhivicion de obras de artistas locales</descripción>
        </evento>

        <evento>
            <titulo>Consierto de Jazz</titulo>
            <fecha>2024-04-25</fecha>
            <hora>19:00</hora>
            <descripción>actiación en vivo de una banda de jazz</descripción>
        </evento>
    </eventos>
</agenda>
