=== henadalGH/BD2/Unidad_1/ejercicio2.dtd
<!ELEMENT libros (libro+)>
<!ELEMENT libro (titulo, autor, añoPublicacion, genero)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT añoPublicacion (#PCDATA)>
<!ELEMENT genero (#PCDATA)>

=== henadalGH/BD2/Unidad_1/ejercicio2.xml
<?xml-model href="ejercicio2.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>
<!--<!DOCTYPE libros SYSTEM "ejercicio2.dtd">-->
<libros>
    <libro>
        <titulo>Piense y hagase rico</titulo>    
        <autor>Napoleón Hill</autor>
        <añoPublicacion>1937</añoPublicacion>
        <genero>Lobro de auto ayuda</genero>
    </libro>
    <libro>
        <titulo>No es facil ser Watson</titulo>    
        <autor>Andrea Ferrari</autor>
        <añoPublicacion>2011</añoPublicacion>
        <genero>literatura juvenil</genero>
    </libro>
</libros>
