=== henadalGH/BD2/Unidad_1/ejercicio3.dtd
<!ELEMENT escuela (cursos)>
<!ELEMENT cursos (curso)>
<!ELEMENT curso (profesor)>
<!ELEMENT profesor (alumnos)>
<!ELEMENT alumnos (alumno+)>
<!ELEMENT alumno (nombre, edad, direccion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>

=== henadalGH/BD2/Unidad_1/ejercicio3.xml
<!DOCTYPE escuela SYSTEM "ejercicio3.dtd">
<escuela>
    <cursos>
        <curso>
            <profesor>
                <alumnos>
                    <alumno>
                        <nombre>Juan</nombre>
                        <edad>30</edad>
                        <direccion>Entre Rios 2023</direccion>
                    </alumno>
                    <alumno>
                        <nombre>Maria</nombre>
                        <edad>20</edad>
                        <direccion>Entre Rios 2043</direccion>
                    </alumno>
                </alumnos>
            </profesor>
        </curso>
    </cursos>
</escuela>
