=== henadalGH/BD2/Unidad_1/ejercicio7.dtd
<!ELEMENT almacen (productos)>
<!ELEMENT productos (categorias)>
<!ELEMENT categorias (categoria+)>
<!ELEMENT categoria (nombre, articulos+)>
<!ELEMENT articulos (producto+)>
<!ELEMENT producto (nombre, precio, stock)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT stock (#PCDATA)>

=== henadalGH/BD2/Unidad_1/Ejercicio7.xml
<!DOCTYPE almacen SYSTEM "ejercicio7.dtd">
<almacen>
    <productos>
        <categorias>
            <categoria>
                <nombre>Limpieza</nombre>
                <articulos>                        
                    <producto>
                        <nombre>Detergente líquido</nombre>
                        <precio>450.00</precio>
                        <stock>120</stock>
                    </producto>
                    <producto>
                        <nombre>Lavandina</nombre>
                        <precio>300.00</precio>
                        <stock>85</stock>
                    </producto>
                    <producto>
                        <nombre>Desinfectante multiuso</nombre>
                        <precio>520.00</precio>
                        <stock>60</stock>
                    </producto>
                </articulos>
            </categoria>

            <categoria>
                <nombre>Higiene personal</nombre>
                <articulos>
                    <producto>
                        <nombre>Shampoo</nombre>
                        <precio>750.00</precio>
                        <stock>100</stock>
                    </producto>
                    <producto>
                        <nombre>Jabón en barra</nombre>
                        <precio>250.00</precio>
                        <stock>200</stock>
                    </producto>
                    <producto>
                        <nombre>Pasta dental</nombre>
                        <precio>480.00</precio>
                        <stock>90</stock>
                    </producto>
                </articulos>
            </categoria>    
        </categorias>
    </productos>
</almacen>
